# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.CharField(default='LOCNSZDT001', max_length=64, primary_key=True, serialize=False, unique=True)),
                ('service_name', models.CharField(default='IoT Service', max_length=64)),
                ('max_nodes', models.IntegerField(default=9999)),
                ('url', models.URLField(default='www.xiaoxiezi.net')),
                ('description', models.CharField(default='no description.', max_length=3000)),
                ('rule', models.CharField(default='{"Desc":[{"From":16,"To":1,"Type":"enum","prefix":"地磁:","enum": {"0":"无车","1":"有车"}},{"From":12,"To":4,"Type":"enum","prefix":"类型:","enum": {"0":"检测","1":"检测","2":"心跳"}},{"From":17,"To":7,"Type":"numerical","prefix":"电量: ","suffix":"%"}]}', max_length=3000)),
                ('register_time', models.DateTimeField(auto_now_add=True)),
                ('register_nodes', models.IntegerField(default=0)),
                ('active_nodes', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('service_id', 'service_name'),
            },
        ),
    ]
