# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(default='ffff', max_length=64)),
                ('service_name', models.CharField(default='no name', max_length=64)),
                ('max_nodes', models.IntegerField(default=9999)),
                ('url', models.URLField(default='www.iot.com')),
                ('description', models.CharField(default='no name', max_length=3000)),
            ],
            options={
                'ordering': ('service_id', 'service_name'),
            },
        ),
    ]
