# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-24 05:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='rule',
        ),
    ]
