# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='active_nodes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='service',
            name='register_nodes',
            field=models.IntegerField(default=0),
        ),
    ]
