# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.CharField(default='no description.', max_length=3000),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_id',
            field=models.CharField(default='LOCNSZDT001', max_length=64),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_name',
            field=models.CharField(default='IoT Service', max_length=64),
        ),
    ]
