# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-24 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_rule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='id',
        ),
        migrations.AlterField(
            model_name='service',
            name='service_id',
            field=models.CharField(default='LOCNSZDT001', max_length=64, primary_key=True, serialize=False),
        ),
    ]
