# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20170624_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_id',
            field=models.CharField(default='LOCNSZDT001', max_length=64, primary_key=True, serialize=False, unique=True),
        ),
    ]
