# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 14:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20170626_2153'),
        ('services', '0004_service_rule'),
    ]

    operations = [
    ]
