# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_merge_20170626_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_id',
            field=models.CharField(default='LOCNSZDT001', max_length=64, primary_key=True, serialize=False, unique=True),
        ),
    ]
