# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateways', '0003_auto_20170702_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gateway',
            name='gateway_type',
            field=models.CharField(choices=[('LoRa', 'LoRa'), ('NB-IOT', 'NB-IOT'), ('others', 'others')], default='LoRa', max_length=64),
        ),
    ]
