# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateways', '0004_auto_20170702_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gateway',
            name='id',
        ),
        migrations.AlterField(
            model_name='gateway',
            name='gateway_id',
            field=models.CharField(default='ffff', max_length=64, primary_key=True, serialize=False, unique=True),
        ),
    ]
