# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateways', '0005_auto_20170702_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateway',
            name='max_data_record',
            field=models.BigIntegerField(default=100000000),
        ),
    ]
