# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-16 08:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gateways', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoRaNode',
            fields=[
                ('node_id', models.CharField(default='ffff', max_length=64, primary_key=True, serialize=False, unique=True)),
                ('node_name', models.CharField(default='no name', max_length=64)),
                ('node_type', models.CharField(choices=[('sensor', 'sensor'), ('switch', 'switch'), ('buzzer', 'buzzer'), ('others', 'others')], default='sensor', max_length=64)),
                ('latitude', models.DecimalField(decimal_places=6, default=113.957666, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, default=22.523888, max_digits=9)),
                ('register_time', models.DateTimeField(auto_now_add=True)),
                ('Lastalive_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('device_control', models.CharField(choices=[('ENABLED', 'ENABLED'), ('DISABLED', 'DISABLED')], default='ENABLED', max_length=32)),
                ('device_status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=32)),
                ('max_data_record', models.BigIntegerField(default=100000000)),
                ('heartbeat_interval', models.IntegerField(default=60)),
                ('battery', models.CharField(default='99%', max_length=64)),
                ('EUI', models.CharField(default='eeee', max_length=64, unique=True)),
                ('DevAddr', models.CharField(default='ffff', max_length=64, unique=True)),
                ('AppKey', models.CharField(default='', max_length=256)),
                ('NwkSKey', models.CharField(default='', max_length=256)),
                ('AppSKey', models.CharField(default='', max_length=254)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Service')),
            ],
            options={
                'ordering': ('EUI', 'node_type', 'register_time'),
            },
        ),
        migrations.CreateModel(
            name='NodeRawData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(default='', max_length=128)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('gateway', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gateways.Gateway')),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nodes.LoRaNode')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info1', models.CharField(default='info1', max_length=128)),
                ('info2', models.CharField(default='', max_length=128)),
                ('info3', models.CharField(default='', max_length=128)),
                ('data1', models.CharField(default='', max_length=128)),
                ('data2', models.CharField(default='', max_length=128)),
                ('data3', models.CharField(default='', max_length=128)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('gateway', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gateways.Gateway')),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nodes.LoRaNode')),
            ],
        ),
    ]
