# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-24 01:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gateways', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(default='ffff', max_length=64)),
                ('node_name', models.CharField(default='no name', max_length=64)),
                ('node_type', models.CharField(choices=[('sensor', 'sensor'), ('switch', 'switch'), ('buzzer', 'buzzer'), ('others', 'others')], default='sensor', max_length=64)),
                ('latitude', models.DecimalField(decimal_places=6, default=113.957666, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, default=22.523888, max_digits=9)),
                ('register_time', models.DateTimeField(auto_now_add=True)),
                ('Lastalive_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('device_status', models.CharField(choices=[('ENABLED', 'ENABLED'), ('DISABLED', 'DISABLED')], default='ENABLED', max_length=32)),
            ],
            options={
                'ordering': ('node_id', 'node_type', 'register_time'),
            },
        ),
        migrations.CreateModel(
            name='NodeRawData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(default='', max_length=128)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('gateway', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gateways.Gateway')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info1', models.CharField(default='', max_length=128)),
                ('info2', models.CharField(default='', max_length=128)),
                ('info3', models.CharField(default='', max_length=128)),
                ('data1', models.CharField(default='', max_length=128)),
                ('data2', models.CharField(default='', max_length=128)),
                ('data3', models.CharField(default='', max_length=128)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('gateway', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gateways.Gateway')),
            ],
        ),
        migrations.CreateModel(
            name='LoRaNode',
            fields=[
                ('node_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nodes.Node')),
                ('EUI', models.CharField(default='ffff', max_length=64)),
                ('DevAddr', models.GenericIPAddressField(default='127.0.0.1', unpack_ipv4=True)),
                ('AppKey', models.CharField(default='', max_length=256)),
                ('NwkSKey', models.CharField(default='', max_length=256)),
                ('AppSKey', models.CharField(default='', max_length=254)),
            ],
            options={
                'ordering': ('EUI', 'node_type', 'register_time'),
            },
            bases=('nodes.node',),
        ),
        migrations.AddField(
            model_name='node',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Service'),
        ),
        migrations.AddField(
            model_name='servicedata',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nodes.LoRaNode'),
        ),
        migrations.AddField(
            model_name='noderawdata',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nodes.LoRaNode'),
        ),
    ]
