# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-24 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='id',
        ),
        migrations.AlterField(
            model_name='node',
            name='node_id',
            field=models.CharField(default='ffff', max_length=64, primary_key=True, serialize=False),
        ),
    ]
