# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='device_control',
            field=models.CharField(choices=[('ENABLED', 'ENABLED'), ('DISABLED', 'DISABLED')], default='ENABLED', max_length=32),
        ),
        migrations.AlterField(
            model_name='node',
            name='device_status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=32),
        ),
    ]
