# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0002_auto_20170624_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noderawdata',
            name='id',
        ),
        migrations.AlterField(
            model_name='loranode',
            name='EUI',
            field=models.CharField(default='ffff', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='node_id',
            field=models.CharField(default='ffff', max_length=64, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='noderawdata',
            name='data',
            field=models.CharField(default='', max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='servicedata',
            name='info1',
            field=models.CharField(default='info1', max_length=128),
        ),
    ]
