# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0003_auto_20170626_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='noderawdata',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='noderawdata',
            name='data',
            field=models.CharField(default='', max_length=128),
        ),
    ]
